export interface Types {}
// Generated by https://quicktype.io

export interface Rooms {
  rooms: Room[];
}

export interface Room {
  id?: number | undefined | null;
  type?: string | undefined | null;
  price: number | undefined | null;
  room_number?: number | undefined | null;
  imgs?: string | undefined | null;
}
