export interface Types {}
// Generated by https://quicktype.io

export interface Rooms {
  rooms: Room[];
}

export interface Room {
  id?: number | undefined | null;
  type?: string | undefined | null;
  price: number | undefined | null;
  room_number?: number | undefined | null;
  imgs?: string | undefined | null;
}
// Generated by https://quicktype.io

export interface filteredBooked {
  data: Datum[];
}

export interface Datum {
  reservation_ids: number[];
  rooms: number[];
  total: number;
  check_in: string;
  check_out: string;
  personal_id: string;
  name: string;
  pagination_ids: number;
}
