export interface Types {}
// Generated by https://quicktype.io

export interface Rooms {
  rooms: Room[];
}

export interface Room {
  id: number;
  type: string;
  price: number;
  room_number: number;
  imgs: string;
}
